# Generated by Django 5.1.1 on 2024-09-13 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_bannercontent_teammember_delete_home'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BannerContent',
            new_name='Banner',
        ),
        migrations.RenameModel(
            old_name='TeamMember',
            new_name='Team',
        ),
    ]
