# Generated by Django 5.1.1 on 2024-09-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_bannercontent_banner_rename_teammember_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команда'},
        ),
    ]
